Cancelling of concurrent pipeline run due to milestone wrongly claims that user aborted
jenkinsci/pipeline-milestone-step-plugin pull request #29
Opened 2021-11-05 10:03 UTC by reinholdfuereder

See JENKINS-67067 "Cancelling of concurrent pipeline run due to milestone wrongly claims that user aborted via FlowInterruptedException#actualInterruption"

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2021-11-05 10:10 UTC, reinholdfuereder commented
@amuniz  I think the check fails due to a kind of infrastructure or dependency problem: namely the dependency on very old Jenkins core version?

2021-11-05 19:45 UTC, jglick reviewed
OK I think but could use test coverage.

2021-11-05 21:15 UTC, jglick commented
IIUC @dwnusbaum says this is incorrect.

2021-11-05 21:17 UTC, dwnusbaum requested changes

2021-11-05 21:17 UTC, dwnusbaum commented on src/main/java/org/jenkinsci/plugins/pipeline/milestone/MilestoneStepExecution.java
> +            throw new FlowInterruptedException(Result.NOT_BUILT, false, new CancelledCause(job + "#" + build));
You should only change this argument to `false` if this exception should be considered a non-fatal problem that would make sense for something like the `retry` step to retry. As far as I understand, that is not the case for this exception.

2021-11-06 12:01 UTC, reinholdfuereder commented
Thanks @jglick and @dwnusbaum for your enlightenment: I seemingly wrongly thought that I can use this `FlowInterruptedException#isActualInterruption()` to differentiate between (a) an interruption from a user clicking on abort the build and (b) all other interruptions.
Presumably because I wasn't reading the JavaDoc carefully enough:
{code}
actualInterruption – true if this is an actual build interruption (e.g. the user wants to abort the build)
{code}
=> the user wants to abort the build is ONE example, NOT the ONLY state/situation/example

=> Sorry, if I know understand it correctly (thanks to @dwnusbaum explanation), then this PR and the Jenkins ticket are definitely incorrect => I will close them therefore

2021-11-06 12:01 UTC, closed without merging